"""
shaders.py – GLSL Code and Compilation Utilities. Defines GLSL shaders and compiles them 
into OpenGL objects — requires an active OpenGL context.
"""

from __future__ import annotations
from OpenGL import GL

GLYPH_NONE = 255
GLYPH_PLUS = 31    # "+"
GLYPH_MINUS = 32    # "−"
GLYPH_BLANK = 33    # empty face
MAX_FACES = 24
MAX_GLYPHS = 34 # index 0–33 (GLYPH _BLANK included); 255=GLYPH NONE is excluded


DICE_VERT = """
#version 330 core

layout(location = 0) in vec3  a_position;
layout(location = 1) in vec3  a_normal;
layout(location = 2) in vec2  a_uv;
layout(location = 3) in float a_face_idx;

uniform mat4 u_model;
uniform mat4 u_view_proj;
uniform mat3 u_normal_mat;

out vec3  v_normal_world;
out vec3  v_frag_pos;
out vec2  v_uv;
flat out int v_face_idx;

void main() {
    vec4 world_pos  = u_model * vec4(a_position, 1.0);
    v_frag_pos      = world_pos.xyz;
    v_normal_world  = normalize(u_normal_mat * a_normal);
    v_uv            = a_uv;
    v_face_idx      = int(a_face_idx + 0.5);
    gl_Position     = u_view_proj * world_pos;
}
"""

DICE_FRAG = """
#version 330 core

in  vec3  v_normal_world;
in  vec3  v_frag_pos;
in  vec2  v_uv;
flat in int v_face_idx;

out vec4 frag_color;

uniform vec3      u_light_dir;
uniform vec3      u_light_color;
uniform vec3      u_dice_color;
uniform vec3      u_glyph_color;
uniform float     u_shininess;
uniform bool      u_highlight;
uniform vec3      u_cam_pos;
uniform int       u_face_glyphs[24];
uniform sampler2D u_glyph_atlas;
uniform vec4      u_glyph_uvs[10];
uniform vec4      u_glyph_uv_plus;
uniform vec4      u_glyph_uv_minus;

// ── MSDF ─────────────────────────────────────────────────────────────────────
// distanceRange = 2 (value from atlas.json)
// median(r,g,b) converts the multi-channel distance field into coverage.
// screen_px_range scales the transition according to the glyph size on the screen.

#define PX_RANGE     2.0
#define SINGLE_SCALE 0.62
#define PAIR_Y       0.62
#define PAIR_X       0.40
#define PAIR_OFF     0.43

// Independent scales per axis for fudge symbols.
// Calculated from the planeBounds of each glyph so that the visual height corresponds 
// to that of a typical digit (pb_h/SINGLE_SCALE ≈ constant).
// target_visual = 0.7969 / 0.62 ≈ 1.2853
// "+" pb=0.5156×0.5156 → scale = 0.5156/1.2853 ≈ 0.4011 (square, one scale works)
// "-" pb=0.3594×0.1250 → scale_x=0.2796, scale_y=0.0973
// scale_y of the "-" is the most important: it ensures that your 8px of atlas in Y
// cover enough screen pixels for a crisp screen_px_range.

#define PLUS_SCALE   0.4011
#define MINUS_SCALE_X 0.2796
#define MINUS_SCALE_Y 0.2000

float msdf_median(vec3 msd) {
    return max(min(msd.r, msd.g), min(max(msd.r, msd.g), msd.b));
}

float msdf_coverage(vec2 auv) {
    if (auv.x < 0.0) return 0.0;
    vec3  msd = texture(u_glyph_atlas, auv).rgb;
    float sd  = msdf_median(msd);

    // Full Jacobian: measures how many screen pixels per atlas pixel in
    // both UV directions. Using only dFdx(auv.x)+dFdy(auv.y) underestimates the
    // magnitude when there is rotation/perspective, leaving the edges blurred.
    // Averaging width and height corrects non-square atlases.

    vec2  atlas_size = vec2(textureSize(u_glyph_atlas, 0));
    vec2  duv_dx     = vec2(dFdx(auv.x), dFdx(auv.y)) * atlas_size;
    vec2  duv_dy     = vec2(dFdy(auv.x), dFdy(auv.y)) * atlas_size;
    float screen_px_range = PX_RANGE * 0.5
        * (length(duv_dx) + length(duv_dy));
    screen_px_range = max(screen_px_range, 1.0);
    return clamp((sd - 0.5) * screen_px_range + 0.5, 0.0, 1.0);
}

// ── UV mapping for the atlas ───────────────────────────────────────────────
//
// Distortion problem: the UV rectification of each glyph preserves proportions in atlas pixels 
// (generated by _glyph_to_uv_rect), but if the shader maps [-1,1] independently in X and Y to 
// the rectification, it stretches the glyph to fill the square area — distorting narrow ("1") 
// or wide ("-") glyphs.
//
// Solution: calculate the aspect ratio of the rectification in atlas pixels ar = (du_pixels) / (dv_pixels)
// and scale the local minor axis so that the glyph appears with its real proportions, 
// centered (letterbox inside the [-scale, scale]²).

vec2 rect_atlas_uv(vec2 local_xy, vec4 rect) {
    // rect = (u0, v0, u1, v1) in UV normalized [0,1].
    // Calculates aspect ratio in pixels: ar > 1 → wider than tall.

    vec2  atlas_sz = vec2(textureSize(u_glyph_atlas, 0));
    float du_px    = (rect.z - rect.x) * atlas_sz.x;
    float dv_px    = (rect.w - rect.y) * atlas_sz.y;
    float ar       = (dv_px > 1e-4) ? (du_px / dv_px) : 1.0;

    // Compresses the minor axis: local_xy ∈ [-1,1]², but only the range
    // [-1/ar, 1/ar] in X (if ar < 1) or [-ar, ar] in Y (if ar > 1)
    // corresponds to the real glyph. Outside of this → discard (-1.0).

    vec2 scaled;
    if (ar >= 1.0) {
        // Mais largo que alto: comprimir Y
        scaled = vec2(local_xy.x, local_xy.y * ar);
    } else {
        // Mais alto que largo: comprimir X
        scaled = vec2(local_xy.x / ar, local_xy.y);
    }
    if (abs(scaled.x) > 1.0 || abs(scaled.y) > 1.0) return vec2(-1.0);

    vec2 n = scaled * 0.5 + 0.5;
    // rect.y = v0 (top OpenGL), rect.w = v1 (base OpenGL) for digits; 
    // interpolates U from rect.x→rect.z, V from rect.w→rect.y (Y already inverted by Python).

    return vec2(mix(rect.x, rect.z, n.x), mix(rect.w, rect.y, n.y));
}

vec2 digit_atlas_uv(vec2 uv, int digit, float offset_x, float x_scale, float y_scale) {
    vec2 local = vec2((uv.x - offset_x) / x_scale, uv.y / y_scale);
    if (abs(local.x) > 1.0 || abs(local.y) > 1.0) return vec2(-1.0);
    return rect_atlas_uv(local, u_glyph_uvs[digit]);
}

vec2 symbol_atlas_uv(vec2 uv, vec4 rect, float scale_x, float scale_y) {
    vec2 local = vec2(uv.x / scale_x, uv.y / scale_y);
    if (abs(local.x) > 1.0 || abs(local.y) > 1.0) return vec2(-1.0);
    return rect_atlas_uv(local, rect);
}

// ── MSDF coverage by glyph type ─────────────────────────────────────────

float glyph_coverage(vec2 uv, int glyph_id) {
    if (glyph_id == 255) return 0.0;
    if (glyph_id == 33)  return 0.0;

    float edge_mask = 1.0 - smoothstep(0.78, 0.82, length(uv));

    if (glyph_id >= 0 && glyph_id <= 9) {
        vec2 auv = digit_atlas_uv(uv, glyph_id, 0.0, SINGLE_SCALE, SINGLE_SCALE);
        return msdf_coverage(auv) * edge_mask;

    } else if (glyph_id >= 10 && glyph_id <= 20) {
        int  tens  = glyph_id / 10;
        int  units = glyph_id - tens * 10;
        vec2 lv    = digit_atlas_uv(uv, tens,  -PAIR_OFF, PAIR_X, PAIR_Y);
        vec2 rv    = digit_atlas_uv(uv, units,  PAIR_OFF, PAIR_X, PAIR_Y);
        return max(msdf_coverage(lv), msdf_coverage(rv)) * edge_mask;

    } else if (glyph_id >= 21 && glyph_id <= 30) {
        int  td = glyph_id - 21;
        vec2 lv = digit_atlas_uv(uv, td, -PAIR_OFF, PAIR_X, PAIR_Y);
        vec2 rv = digit_atlas_uv(uv,  0,  PAIR_OFF, PAIR_X, PAIR_Y);
        return max(msdf_coverage(lv), msdf_coverage(rv)) * edge_mask;

    } else if (glyph_id == 31) {
        vec2 auv = symbol_atlas_uv(uv, u_glyph_uv_plus,  PLUS_SCALE,    PLUS_SCALE);
        return msdf_coverage(auv) * edge_mask;

    } else if (glyph_id == 32) {
        vec2 auv = symbol_atlas_uv(uv, u_glyph_uv_minus, MINUS_SCALE_X, MINUS_SCALE_Y);
        return msdf_coverage(auv) * edge_mask;
    }

    return 0.0;
}

// ── Blinn-Phong lighting + rim light ───────────────────────────────────────

void main() {
    vec3 N = normalize(v_normal_world);
    vec3 L = normalize(u_light_dir);
    vec3 V = normalize(u_cam_pos - v_frag_pos);
    vec3 H = normalize(L + V);

    vec3 base_color = u_highlight
        ? mix(u_dice_color, vec3(1.0, 0.85, 0.1), 0.45)
        : u_dice_color;

    int   glyph_id       = (v_face_idx >= 0 && v_face_idx < 24)
                           ? u_face_glyphs[v_face_idx] : 255;
    float glyph_mask_val = glyph_coverage(v_uv, glyph_id);

    float NdotL = max(dot(N, L), 0.0);
    float NdotH = max(dot(N, H), 0.0);

    vec3  sky     = vec3(0.45, 0.50, 0.60);
    vec3  ground  = vec3(0.18, 0.16, 0.14);
    vec3  ambient = mix(ground, sky, N.y * 0.5 + 0.5) * 0.55;
    float diff    = NdotL * 0.85;
    float rim_f   = pow(1.0 - max(dot(N, V), 0.0), 3.0);
    vec3  rim_v   = rim_f * vec3(0.12, 0.14, 0.18) * 0.6;

    float spec_broad  = pow(NdotH, u_shininess * 0.25) * 0.15;
    float spec_sharp  = pow(NdotH, u_shininess)        * 0.55;
    float spec_total  = (spec_broad + spec_sharp) * step(0.001, NdotL);

    vec3 lit_color = (ambient + diff * u_light_color + rim_v) * base_color
                   + spec_total * u_light_color;

    if (glyph_mask_val > 0.0) {
        vec3 glyph_lit = (ambient + diff * u_light_color) * u_glyph_color
                       + spec_total * u_light_color * 0.4;
        lit_color = mix(lit_color, glyph_lit, glyph_mask_val);
    }

    lit_color  = pow(clamp(lit_color, 0.0, 1.0), vec3(1.0 / 1.8));
    frag_color = vec4(lit_color, 1.0);
}
"""

GROUND_VERT = """
#version 330 core

layout(location = 0) in vec3 a_position;

uniform mat4 u_view_proj;

out vec2 v_uv;

void main() {
    v_uv        = a_position.xz * 0.5;
    gl_Position = u_view_proj * vec4(a_position, 1.0);
}
"""

GROUND_FRAG = """
#version 330 core

in  vec2 v_uv;
out vec4 frag_color;

vec4 grid(vec2 uv, float spacing) {
    vec2 wrapped = abs(fract(uv / spacing) - 0.5);
    vec2 dv      = fwidth(uv / spacing);
    vec2 line    = smoothstep(vec2(0.0), dv * 1.5, wrapped);
    float val    = 1.0 - min(line.x, line.y);
    return vec4(0.35, 0.35, 0.35, val * 0.7);
}

void main() {
    vec4 g1 = grid(v_uv, 1.0);
    vec4 g2 = grid(v_uv, 5.0);
    vec4 base = vec4(0.12, 0.12, 0.14, 1.0);
    frag_color = mix(base, vec4(0.5, 0.5, 0.5, 1.0), g2.a * 0.5 + g1.a * 0.25);
}
"""


class ShaderError(RuntimeError):
    pass


def _compile_shader(source: str, shader_type: int) -> int:
    
    shader = GL.glCreateShader(shader_type)

    GL.glShaderSource(shader, source)
    GL.glCompileShader(shader)

    if not GL.glGetShaderiv(shader, GL.GL_COMPILE_STATUS):
        log = GL.glGetShaderInfoLog(shader).decode()
        kind = "vertex" if shader_type == GL.GL_VERTEX_SHADER else "fragment"
        GL.glDeleteShader(shader)

        raise ShaderError(f"Failed to compile shader {kind}:\n{log}")
    
    return shader


def _link_program(vert: int, frag: int) -> int:
    
    program = GL.glCreateProgram()
    
    GL.glAttachShader(program, vert)
    GL.glAttachShader(program, frag)
    GL.glLinkProgram(program)
    GL.glDeleteShader(vert)
    GL.glDeleteShader(frag)

    if not GL.glGetProgramiv(program, GL.GL_LINK_STATUS):
        log = GL.glGetProgramInfoLog(program).decode()
        GL.glDeleteProgram(program)

        raise ShaderError(f"Failed to link program:\n{log}")
    
    return program


def build_program(vert_src: str, frag_src: str) -> int:
    vert = _compile_shader(vert_src, GL.GL_VERTEX_SHADER)
    frag = _compile_shader(frag_src, GL.GL_FRAGMENT_SHADER)
    return _link_program(vert, frag)


def build_dice_program() -> int:
    return build_program(DICE_VERT, DICE_FRAG)


def build_ground_program() -> int:
    return build_program(GROUND_VERT, GROUND_FRAG)

# Helpers


def set_uniform_mat4(program: int, name: str, mat) -> None:
    import numpy as np
    
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniformMatrix4fv(loc, 1, GL.GL_FALSE, mat.T.astype(np.float32))


def set_uniform_mat3(program: int, name: str, mat) -> None:
    import numpy as np
    
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniformMatrix3fv(loc, 1, GL.GL_FALSE, mat.T.astype(np.float32))


def set_uniform_vec3(program: int, name: str, v) -> None:
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniform3f(loc, float(v[0]), float(v[1]), float(v[2]))


def set_uniform_float(program: int, name: str, val: float) -> None:
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniform1f(loc, float(val))


def set_uniform_bool(program: int, name: str, val: bool) -> None:
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniform1i(loc, int(val))


def set_uniform_int_array(program: int, name: str, values: list[int]) -> None:
    """Sends array of ints to uniform int[]."""    
    
    for i, v in enumerate(values):
        loc = GL.glGetUniformLocation(program, f"{name}[{i}]")

        if loc != -1:
            GL.glUniform1i(loc, int(v))


def set_uniform_int(program: int, name: str, val: int) -> None:
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniform1i(loc, int(val))


def set_uniform_vec4(program: int, name: str, v) -> None:
    loc = GL.glGetUniformLocation(program, name)
    if loc != -1:
        GL.glUniform4f(loc, float(v[0]), float(v[1]), float(v[2]), float(v[3]))


def set_uniform_vec4_array(program: int, name: str, data: "np.ndarray") -> None:
    """
    Send array of vec4 to uniform vec4[]. 
    data: float32 (N, 4)
    """
    import numpy as np

    arr = data.astype(np.float32)

    for i, row in enumerate(arr):
        loc = GL.glGetUniformLocation(program, f"{name}[{i}]")

        if loc != -1:
            GL.glUniform4f(loc, float(row[0]), float(
                row[1]), float(row[2]), float(row[3]))

# Atlas UV table


def _glyph_to_uv_rect(glyph: dict, atlas_w: float, atlas_h: float) -> "np.ndarray":
    """
    Returns the atlasBounds of the glyph converted to UV normalized [0,1].

    Y Convention: yOrigin=bottom in the atlas → inverted for OpenGL (v=0 is top).    
    """
    import numpy as np

    ab = glyph["atlasBounds"]
    u0 = ab["left"] / atlas_w
    u1 = ab["right"] / atlas_w
    v0 = 1.0 - ab["top"] / atlas_h
    v1 = 1.0 - ab["bottom"] / atlas_h

    return np.array([u0, v0, u1, v1], dtype=np.float32)


def _build_unicode_index(atlas_json: dict) -> dict:
    glyphs_by_unicode = {}

    for glyph in atlas_json.get("glyphs", []):
        if "atlasBounds" not in glyph:
            continue

        glyphs_by_unicode[glyph["unicode"]] = glyph

    return glyphs_by_unicode


def _build_glyph_uvs_from_list(
    by_unicode: dict,
    atlas_w: float,
    atlas_h: float,
) -> "tuple[np.ndarray, np.ndarray, np.ndarray]":

    import numpy as np

    zero4 = np.zeros(4, dtype=np.float32)

    table = np.zeros((10, 4), dtype=np.float32)

    for digit in range(10):
        cp = 48 + digit

        if cp in by_unicode:
            table[digit] = _glyph_to_uv_rect(by_unicode[cp], atlas_w, atlas_h)

    plus_rect = (_glyph_to_uv_rect(by_unicode[43], atlas_w, atlas_h)
                 if 43 in by_unicode else zero4.copy())
    
    minus_rect = (_glyph_to_uv_rect(by_unicode[45], atlas_w, atlas_h)
                  if 45 in by_unicode else zero4.copy())

    return table, plus_rect, minus_rect


def build_glyph_uv_table(atlas_json: dict) -> "np.ndarray":
    """
    Returns float32(10, 4) with the rects(u0,v0,u1,v1) of digits 0–9.

    Index i == digit i.

    The UVs are adjusted by planeBounds so that the shader correctly maps the 
    local UV [-1,1] to the glyph region in the atlas, without leaking to neighboring glyphs.
    """
    import numpy as np

    atlas_info = atlas_json.get("atlas", {})
    atlas_w = float(atlas_info.get("width",  1))
    atlas_h = float(atlas_info.get("height", 1))

    glyphs_raw = atlas_json.get("glyphs", {})

    if isinstance(glyphs_raw, list):
        by_unicode = _build_unicode_index(atlas_json)
        table, _, _ = _build_glyph_uvs_from_list(by_unicode, atlas_w, atlas_h)

        return table
    
    else:
        table = np.zeros((10, 4), dtype=np.float32)

        for i in range(10):
            key = str(i)

            if key in glyphs_raw:
                g = glyphs_raw[key]
                table[i] = [g["u0"], g["v0"], g["u1"], g["v1"]]

        return table


def build_symbol_uvs(atlas_json: dict) -> "tuple[np.ndarray, np.ndarray]":
    """
    Returns (plus_rect, minus_rect) as float32 shape arrays (4,).    
    """
    import numpy as np
    zero4 = np.zeros(4, dtype=np.float32)

    atlas_info = atlas_json.get("atlas", {})
    atlas_w = float(atlas_info.get("width",  1))
    atlas_h = float(atlas_info.get("height", 1))

    glyphs_raw = atlas_json.get("glyphs", {})

    if isinstance(glyphs_raw, list):
        by_unicode = _build_unicode_index(atlas_json)
        _, plus_rect, minus_rect = _build_glyph_uvs_from_list(
            by_unicode, atlas_w, atlas_h)
        
        return plus_rect, minus_rect
    
    else:
        def _rect(key):
            if key in glyphs_raw:
                g = glyphs_raw[key]
                return np.array([g["u0"], g["v0"], g["u1"], g["v1"]], dtype=np.float32)
            
            return zero4.copy()
        
        return _rect("+"), _rect("-")
